[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python db/init_db.py"]

[start]
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"